### ISSUE TITLE
Use in publication

### ISSUE THREAD

**Issue by kvistgaard** [Sansui233/logseq-bonofix-theme#11]
Currently, the theme is not applied when publishing the pages, neither if is added through the marketplace nor by adding @import url('https://cdn.jsdelivr.net/gh/sansui233/logseq-bonofix-theme/custom.css') to the ...static/css/custom.css

**Comment by Sansui233** [comment]
Logseq doesn't export custom theme when publishing. To customize published pages, replace the custom.css in the static/css in your publish directory.

**Comment by kvistgaard** [comment]
Yes, that's what I'm doing, I changing costum.css in the export folder. All customizations work except the theme
Here's my custom.css from the publication folder:
```css
@import url('https://cdn.jsdelivr.net/gh/sansui233/logseq-bonofix-theme/custom.css')
#head .ui__dropdown-trigger,
#left-sidebar .flashcards-nav,
#left-sidebar .all-pages-nav,
#left-sidebar .favorites,
#left-sidebar .recent,
#right-sidebar .cp__right-sidebar-settings div:last-child {
    display: none;
}

a.delete {
  display: none;
}
```
