### ISSUE TITLE
如何更改calendar 图标

### ISSUE THREAD

**Issue by yunzhongxicao** [Sansui233/logseq-bonofix-theme#12]
都是3.6.2版本，在一台电脑上显示为：
![image](https://user-images.githubusercontent.com/52601843/160880753-ab51eac6-8a67-45d6-acad-e33f90fbc70f.png)
另一台电脑上是蓝色的，如何改为上图这种红色的：
![image](https://user-images.githubusercontent.com/52601843/160880886-6f605833-0fd3-40b7-a1d0-bd69af7e714e.png)

**Comment by Sansui233** [comment]
图标样式取决于系统emoji。如果自己想修改为其他图标，首先不能使用插件版的主题（除非直接修改插件），只能使用自己库里的custom.css。其次你需要找到一个合适的svg图标，并在custom.css后添加：

```css
#main-content-container .journal h1.title:before,
#main-content-container .is-journals h1.title:before {
  content: url('data:image/svg+xml;charset=utf8,这里放URL编码');
}
```
