### ISSUE TITLE
How to use custom fonts？

### ISSUE THREAD

**Issue by Littlecowherd** [Sansui233/logseq-bonofix-theme#13]
Is it possible to make the font a configuration item instead of directly modifying the CSS file?

**Comment by Sansui233** [comment]
A pure plugin theme can't be configured because theme is generated at build time instead of plugin runtime. Instead, you can still customize any theme with `custom.css` in your graph.

Reset theme to default. Then modify the `custom.css` file in your own graph (not the file in plugin).

```css
@import url('https://cdn.jsdelivr.net/gh/sansui233/logseq-bonofix-theme/custom.css');

:root {
  --ls-font-family: Overpass;
}
```

Theme variables can be found in [official css file](https://github.com/logseq/logseq/blob/master/resources/css/common.css)

You can search the `custom.css` file in your graph and edit it in Logseq. But I would like to recommend editing the file using external editor to avoid the delay of writing file to disk.
