### ISSUE TITLE
暗黑模式下块的点不清晰

### ISSUE THREAD

**Issue by mendax1234** [Sansui233/logseq-bonofix-theme#16]
在暗黑模式下，每个块对应的点不太清晰，效果大概如下图，希望能早日修复！
![image](https://user-images.githubusercontent.com/62934294/169779903-a437f993-7ff9-4f6b-901d-292d202a6b18.png)

**Comment by Sansui233** [comment]
这一点是刻意为之。之前的 issue 中提过，此主题的 dark mode 是给身处全黑的环境下无法开灯的人使用的，白天使用此主题的 dark mode 整体对比度将对较弱。这个主题的设计重点之一是干净，在全黑的环境下，这个点是能看清但不会显得吵闹的程度。

**Comment by mendax1234** [comment]
@Sansui233 但是，我觉得大多数人都不是在环境纯黑的情况下开启暗黑模式的吧。其实加一个那个bullet的插件也能在打字的时候看到点。

**Comment by Sansui233** [comment]
@mendax1234 我不确定你的"大多数人"依据是从何而来，由于我自己身边的人都是选择主题跟随系统，此主题从开始设计时便是考虑解决此类需求。如果需要在白天模式下使用黑色主题，自带的就很不错，也可以使用对比度更强的 Bear 等等，bonofix 不是个好选择。

**Comment by mendax1234** [comment]
@Sansui233
 >我不确定你的"大多数人"依据是从何而来，由于我自己身边的人都是选择主题跟随系统，此主题从开始设计时便是考虑解决此类需求。如果需要在白天模式下使用黑色主题，自带的就很不错，也可以使用对比度更强的 Bear 等等，bonofix 不是个好选择。

我也是选择主题跟随系统，那如果是这样的话，晚上太阳落山，就变成暗黑模式。那么，我其实挺好奇为什么现在晚上还会有很多人不开灯工作？难道不都是有个灯吗，所以我才认为其实现在很多人都不太可能晚上处在一个纯黑的环境下工作的，好歹也得有个台灯吧（台灯也不贵……）

**Comment by mendax1234** [comment]
好吧，了解了，谢谢！

**Comment by mendax1234** [comment]
请问主题里的字体能修改吗？
@Sansui233

**Comment by Sansui233** [comment]
@mendax1234 见 #13，所有的颜色和样式都可以改。

**Comment by mendax1234** [comment]
没太看懂，能具体解释一下吗？谢谢

**Comment by Sansui233** [comment]
自定义的话，先把主题切回默认主题，从文件管理器打开你的目前使用 logseq graph，改 custom.css 的内容（Logseq 里也搜得到这个文件，但我这边写入这个文件时极其不同步）
<img width="490" alt="image" src="https://user-images.githubusercontent.com/27474981/169816334-6b92ac39-70cf-4852-bdc9-b3ddd6995b02.png">

```css
@import url('https://cdn.jsdelivr.net/gh/sansui233/logseq-bonofix-theme/custom.css'); /*引入的主题文件*/

:root {
  --ls-font-family: Overpass; /*自定义字体*/
}
```

可自定义的颜色等等可以在 [official css file](https://github.com/logseq/logseq/blob/master/resources/css/common.css) 找到。

**Comment by mendax1234** [comment]
好的，谢谢！但是我改了之后好像还是没有效果。

**Comment by Sansui233** [comment]
首先确定字体是你系统中有的，名字是对的（都是英文名）。然后就是尽量用外部编辑器改这个文件，目前 logseq 的文件同步问题还是有点重。改完后 ctrl + r 刷新页面。

**Comment by mendax1234** [comment]
好的，那能否提供一下日历emoji的相关代码，我加到我自己的主题看看，谢谢！

**Comment by Sansui233** [comment]
```css
.journal h1.title:before,
.is-journals h1.title:before {
  content: "🗓";
  vertical-align: text-bottom;
  margin-right: 0.3em;
  font-size: 0.75em;
}
```
