### ISSUE TITLE
Changing colors for TODO button

### ISSUE THREAD

**Issue by feyzee** [Sansui233/logseq-bonofix-theme#22]
How to change color for the button text(NOW, LATER, TODO & DOING) and the background?

![image](https://user-images.githubusercontent.com/11005389/193768691-5d4028ca-70fb-4f61-bf7f-6350648b01f2.png)

**Comment by feyzee** [comment]
i had some luck by adding custom.css - [used this commit from logseq github theme](https://github.com/g1eny0ung/logseq-github-theme/commit/6052b9ce4f0287d8510d978069b666bfce69dd7b). it does work for changing the text color but not for the background.

![image](https://user-images.githubusercontent.com/11005389/193769682-918d0f74-29a9-41bf-b115-4bfd301ca8ae.png)

**Comment by Sansui233** [comment]
Update to the latest theme version and here are the two variables

```css
.dark-theme,
html[data-theme="dark"]{
  --bf-tag-background-color: #3f74ae;
  --bf-tag-background-hover-color: #5f97c0;
}
```

The solution is for your logseq version. The lastest logseq has improved its overall design and the selectors above won't work.

**Comment by feyzee** [comment]
Above variables are changing colors for the tags. I've found `ls-page-checkbox-color` changes the color of the TODO/DOING.
Now is there way to change only for DOING and not TODO?

```css
.dark-theme,
html[data-theme="dark"]{
  --ls-page-checkbox-color: #0b9b00;
}
```

Above code will make it look like this 
![image](https://user-images.githubusercontent.com/11005389/194047481-79a356d3-6ff6-4255-99c9-33b903ddd2ed.png)
