### ISSUE TITLE
Stylea are broken for the Tabs plugin

### ISSUE THREAD

**Issue by yougotwill** [Sansui233/logseq-bonofix-theme#27]
I have used the `custom.css` option to improve the styling of the [Tabs](https://github.com/pengx17/logseq-plugin-tabs/) plugin but not sure how to include my changes in this repository (assuming you want to add support for it).

Otherwise this might be useful for other people!

1. Make sure to turn on `tabs:inherit-custom-css Advanced: inherit custom.css styles` in the Tabs plugin.
2. Copy the code below into your `custom.css` file
  ```css
  #app .dark .logseq-tab-wrapper .logseq-tab {
    /* --ls-secondary-background-color */
    background-color: #27282b !important;
    border-color: transparent !important;
    color: rgb(156,163,175) !important;
  }
  
  #app .dark .logseq-tab-wrapper .logseq-tab button:hover {
    /* --ls-quaternary-background-color */
    background-color: #36383b;
  }
  
  #app .light .logseq-tab-wrapper .logseq-tab {
    /* --ls-secondary-background-color */
    background-color: #f8f8f8 !important;
    color: initial !important;
  }
  
  #app .light .logseq-tab-wrapper .logseq-tab button:hover {
    /* --ls-quaternary-background-color */
    background-color: #ebeaea;
  }
  ```

3. Profit 💰 

## Before

<img width="464" alt="Screenshot 2023-03-18 at 10 54 49" src="https://user-images.githubusercontent.com/14887287/226071668-070820bd-5ffe-4815-992d-dd2ba7b62bf0.png">

<img width="471" alt="Screenshot 2023-03-18 at 10 54 58" src="https://user-images.githubusercontent.com/14887287/226071682-56ba9cf2-12b5-46a1-b2e9-14ac6bcbc8c3.png">

## After

<img width="472" alt="Screenshot 2023-03-18 at 10 52 22" src="https://user-images.githubusercontent.com/14887287/226071704-96518abf-ae58-4062-9cb9-d65ba11638d7.png">

<img width="467" alt="Screenshot 2023-03-18 at 10 52 09" src="https://user-images.githubusercontent.com/14887287/226071717-d8fd906b-0a67-4957-9018-1e270b1ac57b.png">
