### ISSUE TITLE
calender emoji before journal title is 农田

### ISSUE THREAD

**Issue by GoTop** [Sansui233/logseq-bonofix-theme#3]

**Comment by Sansui233** [comment]
What's your OS and Logseq runtime platform (desktop or browser)?

**Comment by aadilayub** [comment]
I have a similar problem, using the desktop app on Fedora Linux 34

![image](https://user-images.githubusercontent.com/31581044/135670194-8f84a7d8-484b-4edd-b237-aa73d42c595c.png)

**Comment by Sansui233** [comment]
Yes, the problem is related to OS's fonts, adding the missing font could solve the problem. Or you can simply append the code below to your `custom.css` to disable that emoji.

```css
#main-content #main-content-container .journal .flex-row.foldable-title h1.title:before {
    display:none;
}
```

Logseq doesn't use a special style selector for linux version, (for me) there's not a good way to adapt Linux yet.

**Comment by aadilayub** [comment]
Would this not be fixed by adding "Noto Color Emoji" as a fallback font here?

```css
  --ls-font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, "Apple Color Emoji", Arial, sans-serif,
    "Segoe UI Emoji", "Segoe UI Symbol";
```

**Comment by Sansui233** [comment]
> Would this not be fixed by adding "Noto Color Emoji" as a fallback font here?
> 
> 
> 
> ```css
> 
>   --ls-font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, "Apple Color Emoji", Arial, sans-serif,
> 
>     "Segoe UI Emoji", "Segoe UI Symbol";
> 
> ```

According to [this article](https://jenciso.github.io/blog/how-setup-your-noto-color-emoji-fonts/), I guess there are some ways for custom emoji to fall to sans-serif or other font-family. (Though I have no idea about how to set up preferred emoji on Fedora distribution)

**Comment by owiecc** [comment]
```css
#main-content #main-content-container .journal .flex-row.foldable-title h1.title:before {
    display:none;
}
```
Does not work for me to disable the emoji. I am on Logseq 0.6.3 and Bonofix 3.6.2. What is the proper selector now?
