### ISSUE TITLE
Tag colors

### ISSUE THREAD

**Issue by joaosimuai** [Sansui233/logseq-bonofix-theme#30]
Is it possible to change them based in properties, colors or any other option? Thanks.

**Comment by Sansui233** [comment]
Sorry for late response. To change the global tag background color in this theme, add the following code to the custom.css file located in your graph:

```css
:root {
   --bf-tag-background-color: your color;
}
```

For specific tag background: 

```css
a.tag[data-ref="your-tag-text"] {
    background: your color;
}
```
