### ISSUE TITLE
Add smart arrow shortcuts, as implemented in the default Logseq theme

### ISSUE THREAD

**Issue by nickdos** [Sansui233/logseq-bonofix-theme#32]
I love this theme but one thing that stands out is the lack of "smart arrows" that the default LogSeq theme has. It would be great if they worked with this theme.

I'm referring to the way when you type `-` followed by `>`, the `->` sequence gets automagically converted to `→` (proper arrow symbol).

See [this issue](https://github.com/logseq/logseq/issues/9019) for a better example.

**Comment by Sansui233** [comment]
This feature is supported by Logseq's default Inter font, meaning it's not a genuine arrow; instead, it simply connects "-" and ">" without any spacing in between to make it look like an arrow.

For such special characters, there is currently no optimal CSS solution because Logseq does not provide the corresponding CSS class. One possible solution is to globally replace it with the default Inter font. To do this, add the following line to your `custom.css`:

```css
:root {
  --ls-font-family: Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, "Apple Color Emoji", Arial, sans-serif,
    "Segoe UI Emoji", "Segoe UI Symbol";
}
```
