### ISSUE TITLE
darker dark

### ISSUE THREAD

**Issue by m1karii** [Sansui233/logseq-bonofix-theme#34]
hi!
I'd like to use this (dark) theme as the one I am currently using hasn't been updated in a long time and doesn't support whiteboards and the default "dark" logseq theme looks more like someone threw up...
I haven't found better theme than this however I have one major issue: it is not dark enough. This results in the text being difficult to read as it appears as if I'm looking through murky glasses. I believe this is influenced by my monitor being forced on 100% brightness due to the way it is set up. My main dark background optically appears to be almost the same dark as the sidebar in the screenshot you provide in the readme (with all other shades of gray scaled accordingly). The text also appears more gray than in the screenshots where it appears to be white but I'm explaining this to myself simply by the background being lighter.
could you make all background colors 10-20% darker? if not so could you at least provide me with a way to do so on my own (that ideally would not break over updates) ?
thanks in advance.

**Comment by Sansui233** [comment]
Hello! I considered the choice of a dark background color taking inspiration from commonly used color schemes since the widespread adoption of dark mode. Currently, the dark color being used matches the background color of Google Search. The text color falls between the highlighted text and normal text on Google Search. The text-to-background contrast is slightly lower than Google, slightly higher than GitHub, but noticeably lower than Notion and OpenAI.

Personally, I'm not a fan of Logseq's default dark green color. However, Logseq allows for choosing the theme color in it's settings. After setting theme color, the dark background changes to a dark gray, which providing sufficient contrast. Feel free to give it a try.

If you want to customize colors by yourself, add this to your `custom.css` located in your graph:

```css
.dark-theme,
html[data-theme="dark"] {
  /* main text */
  --ls-primary-text-color: #cecece;
  --ls-secondary-text-color: #bbb;

  /* main background */
  --ls-primary-background-color: #202124;
  --ls-secondary-background-color: #27282c;
  --ls-tertiary-background-color: #303235;
  --ls-quaternary-background-color: #36383b;
  --ls-left-sidebar-background-color: var(--ls-secondary-background-color);
}
```

**Comment by m1karii** [comment]
wow I didn't know about the theme color changing background. thanks for letting me know. It however seems to be a work in progress so I ended up going with your theme with the following changes to `custom.css`:

```css
.dark-theme,
html[data-theme="dark"] {
    --ls-primary-text-color: #ffffff;
    --ls-link-ref-text-color: #52A5F9;
    --bf-external-link-color: #F33F3F;
}

.content :not(pre)>code {
    color: var(--bf-external-link-color);
}
```
thanks for your help
